### ISSUE TITLE
Error message when using filemanager

### ISSUE THREAD

**Issue by MarcusE1W** [sum01/filemanager-plugin#7]
When I close Micro I see the following error message:

```
filemanager:178: attempt to index a non-table object(nil)
stack traceback:
	filemanager:178: in main chunk
	[G]: ?
```

I think the error is created while Micro is running but you can only be seen on the console after Micro is closed.
This error also appears if Micro is just opened and closed without a file opened and without the tree function used.

I am using Archlinux, Micro 1.3.4 and filemanager 2.1.1

**Comment by sum01** [comment]
You're using my `v3` branch on Micro v1.3.4? It's only meant for Micro >= v1.3.5 since it uses the new read-only setting.
